@include macros.texi
@ifset rawfile
@chapter @previewlatex{} in a nutshell

@end ifset
@c -----------------------
@cindex Readme
Does your neck hurt from turning between previewer windows and the
source too often? This Elisp/@LaTeX{} package will render your displayed
@LaTeX{} equations right into the editing window where they belong.

The purpose of @previewlatex{} is to embed @LaTeX{} environments such as
display math or figures into the source buffers.  By mouse-clicking, you
can open the original text.  After editing, another click will just run
the region in question through @LaTeX{} and redisplay the new results.

@ifclear rawfile
@menu
* Activating preview-latex::    
* Getting started::             
* More documentation::               
* Availability::                
* Contacts::                    
@end menu
@end ifclear

@ifset rawfile
If @previewlatex{} has not come in the form of a preinstalled package
for you, consult the @file{INSTALL} file for installation instructions
(especially, read the Prerequisites section).
@end ifset

@node  Activating preview-latex, Getting started, Introduction, Introduction
@section Activating @previewlatex{}
@cindex Activation
After installation, the package needs to be activated (and remember to
activate @AUCTeX{} too).  Some prepackaged versions are activated upon
installation, but otherwise, the activation line that needs to be added
to your own @file{.emacs} file or to a site-wide initialization file is

@example
(add-hook 'LaTeX-mode-hook #'LaTeX-preview-setup)
@end example

@noindent
For a well-configured prepackaged version, this should be the all you
need to do.  If you installed @previewlatex{} yourself, at least the
line

@example
(autoload 'LaTeX-preview-setup "preview")
@end example

@noindent
is also needed.  And in case the directory to which the Elisp files have
been installed is not known to Emacs, a line like

@example
(add-to-list 'load-path "@var{/whatever/directory}")
@end example

@noindent
needs to be added as well.  

@node Getting started, More documentation, Activating preview-latex, Introduction
@section Getting started

Once activated, @previewlatex{} and its documentation will be accessible
from @AUCTeX{}'s menus.  When you have loaded a @LaTeX{} document, you
should be able to spot ``Preview'' in @AUCTeX{}'s menus. Use the menus,
or press @kbd{C-c C-c g @key{RET}} (for ``Generate Preview'') or
@kbd{C-c C-p C-p} (for ``On/off at point'').  Previews will now be
generated for various objects in your document. You'll see them change
into a roadworks sign when the process is half finished. Note that
you can freely navigate the buffer while this is going on. When the
process is finished you will see the objects typeset in your buffer.

It is a bad idea, however, to edit the buffer before the roadworks signs
appear, since that is the moment when the correlation between the
original text and the buffer locations gets established.  If the buffer
changes before that point of time, the previews will not be placed where
they belong. If you do want to change some obvious error you just
spotted we recommend you stop the background process by pressing
@kbd{C-c C-k}.

To see/edit the @LaTeX{} code for a specific object, put the point (the
cursor) on it and press @kbd{C-c C-p C-p}. Now you can edit the code,
and generate a new preview by again pressing @kbd{C-c C-p C-p}.

If you are using the @code{desktop} package, previews will remain from
one session to the next as long as you don't kill your buffer.

@node More documentation, Availability, Getting started, Introduction
@section More documentation
After the installation, documentation in the form of 
@ifinfo 
@ifclear rawfile
this
@end ifclear
@ifset rawfile
an
@end ifset
@end ifinfo
@ifnotinfo
an
@end ifnotinfo
info manual will be available.  You can access it with the standalone
info reader with

@example
info preview-latex
@end example

@noindent
or with

@example
@kbd{C-h i d m preview-latex @key{RET}}
@end example

@noindent
from inside Emacs. Once @previewlatex{} is activated, the info manual is
also present as the menu entry @samp{LaTeX/Preview/Read documentation}.

Depending on your installation, 
@ifnottex
a printable 
@end ifnottex
@iftex
this printed
@end iftex
manual may also be available in the form of @file{preview-latex.dvi} or
@file{preview-latex.ps}.

Detailed documentation for the @LaTeX{} style used for extracting the
preview images is placed in @file{preview.dvi} in a suitable directory
during installation; on typical teTeX-based systems,

@example
texdoc preview
@end example

@noindent
will display it.

@node  Availability, Contacts, More documentation, Introduction
@section Availability
@cindex Download
@cindex @acronym{CVS} access

The @previewlatex{} project is available at SourceForge.  In addition to
the main source tarball, we provide prebuilt documentation files there
for those lacking a recent enough version of makeinfo, and source and
binary @file{.rpm} files suitable for a recent RedHat system. Anonymous
@acronym{CVS} is available as well. The SourceForge homepage of
@previewlatex{} is @uref{http://sourceforge.net/projects/preview-latex}.

@node  Contacts,  , Availability, Introduction
@section Contacts
@cindex Contacts
@cindex Mailing list

Bug reports should be sent by using @kbd{M-x preview-report-bug
@key{RET}}, as this will fill in a lot of information interesting to
us. Questions, suggestions for new features, and/or pleas for help
should go to @email{preview-latex-devel@@lists.sourceforge.net} (the
@previewlatex{} devel team).  For more information on this mailing list,
send a message with just the word @samp{help} as subject or body to
@email{preview-latex-devel-request@@lists.sourceforge.net} or look at
@uref{http://lists.sourceforge.net/lists/listinfo/preview-latex-devel}.
Please use the command @kbd{M-x preview-report-bug @key{RET}} to report
bugs if possible.

Offers to support further development will be appreciated.  For
developer access, ask on
@email{preview-latex-devel@@lists.sourceforge.net}.

