@include macros.texi
@node Introduction
@chapter Introduction to @AUCTeX{}

This section of the @AUCTeX{} manual gives a brief overview of what
@AUCTeX{} is, and the section is also available as a @file{README} file.
It is @strong{not} an attempt to document @AUCTeX{}.  Real documentation
for @AUCTeX{} is available in the rest of the manual, which you can find
in the @file{doc} directory.

Read the @file{INSTALL} or @file{INSTALL.windows} file respectively for
information about how to install @AUCTeX{}.  The files comprise the same
information as the Installation chapter in the @AUCTeX{} manual.

If you are upgrading from the previous version of @AUCTeX{}, the latest
changes can be found in the @file{CHANGES} file.  If you are upgrading
from an older version, read the History chapter in the @AUCTeX{} manual.

@AUCTeX{} is a comprehensive customizable integrated environment for
writing input files for @TeX{}/@LaTeX{}/@ConTeXt{} using GNU Emacs.

@AUCTeX{} lets you run @TeX{}/@LaTeX{}/@ConTeXt{} and
@LaTeX{}/@ConTeXt{}-related tools, such as a output filters or post
processor from inside Emacs.  Especially `running @LaTeX{}' is
interesting, as @AUCTeX{} lets you browse through the errors @TeX{}
reported, while it moves the cursor directly to the reported error, and
displays some documentation for that particular error.  This will even
work when the document is spread over several files.

@AUCTeX{} automatically indents your `@LaTeX{}-source', not only as you
write it --- you can also let it indent and format an entire document.
It has a special outline feature, which can greatly help you `getting an
overview' of a document.

Apart from these special features, @AUCTeX{} provides a large range of
handy Emacs macros, which in several different ways can help you write
your @LaTeX{}/@ConTeXt{} documents fast and painlessly.

All features of @AUCTeX{} are documented using the GNU Emacs online
documentation system.  That is, documentation for any command is just
a key click away!

@AUCTeX{} is written entirely in Emacs-Lisp, and hence you can easily
add new features for your own needs.  It was not made as part of any
particular employment or project (apart from the @AUCTeX{} project
itself).  @AUCTeX{} is distributed under the `GNU Emacs General Public
License' and may therefore almost freely be copied and redistributed.

The next sections are a short introduction to some `actual' features.
For further information, refer to the built-in online documentation of
@AUCTeX{}.

@section Availability

The most recent version is always available at

@flushright
@url{http://ftp.gnu.org/pub/gnu/auctex/}
@end flushright

WWW users may want to check out the @AUCTeX{} page at

@flushright
@url{http://www.gnu.org/software/auctex/}
@end flushright

@section Contacts

There has been established a mailing list for help, bug reports, feature
requests and general discussion about @AUCTeX{}.  You're very welcome
to join.  Traffic average at an article by day, but they come in bursts.
If you are only interested in information on updates, you could refer to
the newsgroups @samp{comp.text.tex} and @samp{gnu.emacs.sources}.

If you want to contact the @AUCTeX{} mailing list, send a mail with the
subject ``subscribe'' to @email{auctex-request@@gnu.org} in order to
join the general discussion list.  Articles should be sent to
@email{auctex@@gnu.org}.  In a similar way, you can subscribe to the
@email{info-auctex@@gnu.org} list for just getting important
announcements about @AUCTeX{}.  The list @email{bug-auctex@@gnu.org} is
for bug reports which you should usually file with the @kbd{@key{M-x}
TeX-submit-bug-report @key{RET}} command.

For the developers of @AUCTeX{} themselves, there is a discussion list
@email{auctex-devel@@gnu.org}.
