#+TITLE: How to release AUCTeX
#+AUTHOR: Mosè Giordano
#+DATE: [2019-10-31 Thu]

This document describes the steps for AUCTeX maintainers to do a new release of
the package via ELPA, updating the Website and other release related tasks.

** ELPA Release

GNU AUCTeX is hosted as a so-called "externals" package in the GNU ELPA Git
repository.  ELPA is setup to track the ~main~ branch of AUCTeX Git repository
in a way that every commit to AUCTeX repo is fetched to ELPA and a new ELPA
release tarball is created on [[https://elpa.gnu.org/devel/auctex.html][GNU-devel ELPA AUCTeX page]].  The steps for
creating a versioned release are described below.

*** Making an ELPA release [0/5]

The following steps happen in AUCTeX Git repository:

- [ ] In =auctex.el=, edit the line ~;; Version: X.Y.Z~.  X and Y match the
  latest AUCTeX version and Z is incremented for every ELPA release of that
  AUCTeX version.  Z starts with 0.  Incrementing the major numbers X and Y is a
  decision made by the maintainers; currently, there is no fixed rule.
- [ ] In =NEWS.org=, replace the header =[Unreleased]= with =[X.Y.Z] -
  YEAR-MM-DD=.
- [ ] Commit the changes above with
  #+begin_example
  Release GNU AUCTeX X.Y.Z

  * GNU AUCTeX Version X.Y.Z released.
  #+end_example
- [ ] Tag the release with
  #+begin_src shell
    git tag -a auctex-X.Y.Z -m "AUCTeX X.Y.Z release"
  #+end_src
- [ ] Push the changes in files and the new tag with
  #+begin_src shell
    git push
    git push --tags
  #+end_src

This is it.  The new GNU AUCTeX ELPA release will hopefully be available within
a few hours.

*** Caveats

It has happened in the past that a new GNU AUCTeX ELPA release didn't really
appear although all steps in the previous section have been performed.  The
reason was that there has been a new style file whose copyright header didn't
have the correct format, and ELPA's tooling is pretty strict about that.

In order to check that all copyrights are ok, clone/checkout the master branch
of the ELPA Git repository.

#+BEGIN_SRC shell
  # Clone if not done before.
  git clone ssh://<user>@git.savannah.gnu.org/srv/git/emacs/elpa.git
  # Otherwise checkout the master brach
  git checkout master
  # Get the latest changes
  git pull
#+END_SRC

To update the external packages (such as AUCTeX), run ~make externals~ in the
root directory of the ELPA repository.  Then run ~make check_copyrights~ which
looks for all files without FSF-copyright line which are not listed in a
special copyright_exceptions file.  As result, it spits out a diff between the
actual and expected copyright exceptions.  If the diff is empty (or at least
doesn't mention an AUCTeX file), everything is fine.

*** One-time setup

Sometimes it is necessary to make changes to ELPA Git repository itself and
modify the way it handles AUCTeX.  AUCTeX is hosted as a so-called "externals"
package, so the first step is to add the GNU ELPA Git repository as an
additional remote to your AUCTeX Git repository.  In the following example, the
remote name is "elpa".

#+BEGIN_SRC shell
  git remote add elpa ssh://<user>@git.savannah.gnu.org/srv/git/emacs/elpa.git
#+END_SRC

AUCTeX is kept in the ~externals/auctex~ branch of the ELPA repository.

** Website [0/6]

The website is maintained in a CVS repository on Savannah.  Read the
[[https://savannah.gnu.org/cvs/?group=www][Savannah instructions about how to
use CVS for webpages]] (remember to replace =www= with =auctex= as project). The
command to checkout the repository locally should be

#+BEGIN_SRC shell
  cvs -z3 -d:ext:YOUR_USER_NAME@cvs.savannah.gnu.org:/web/auctex co auctex
#+END_SRC

In order to access the [[http://web.cvs.savannah.gnu.org/viewvc/auctex/auctex/][remote CVS repository]], you also need to have the
environment variable =CVS_RSH= set to =ssh=:

#+BEGIN_SRC shell
  export CVS_RSH=ssh
#+END_SRC

You can also browse the [[http://web.cvs.savannah.gnu.org/viewvc/auctex/][content of the CVS repository]].

- [ ] Remove all =manual/{auctex,preview-latex}.*= files, and replace them with
  the =auctex-dist/www/manual/manual/{auctex,preview-latex}.*= files from AUCTeX
  repository
- [ ] Remove all =manual/auctex/*.html= files, and replace them with the
  =auctex-dist/www/manual/manual/auctex.*= files from AUCTeX repository
- [ ] Remove all =manual/preview-latex/*.html= files, and replace them with the
  =auctex-dist/www/manual/manual/preview-latex.*= files from AUCTeX repository
- [ ] Update AUCTeX version and date in files in =src/= directory. When you are
  done, run the script =./genpages.sh=
- [ ] Update the =ChangeLog=
- [ ] Register all changes. You can use for example =vc-mode= in Emacs: [0/3]

  - [ ] Register all new files with =i=
  - [ ] Select all files in the same state with =m= and do check in/out with =v=
  - [ ] To delete files not needed anymore I don’t know a better way than
    deleting them on disk, then manually running the command =cvs remove= in the
    local repository and then in =vc-mode= select all files marked as "removed"
    with =m= and make the change effective with =v=

Simple shell commands to help replacing the old files with the new ones:

#+BEGIN_SRC sh
# Set these variables
AUCTEX_DIR="...."
AUCTEX_WEBPAGES_DIR="...."

rm "${AUCTEX_WEBPAGES_DIR}"/manual/{auctex,preview-latex}.* \
   "${AUCTEX_WEBPAGES_DIR}"/manual/auctex/*.html \
   "${AUCTEX_WEBPAGES_DIR}"/manual/preview-latex/*.html

cp "${AUCTEX_DIR}"/auctex-dist/www/manual/manual/{auctex,preview-latex}.* "${AUCTEX_WEBPAGES_DIR}"/manual/.
cp "${AUCTEX_DIR}"/auctex-dist/www/manual/manual/auctex/* "${AUCTEX_WEBPAGES_DIR}"/manual/auctex/.
cp "${AUCTEX_DIR}"/auctex-dist/www/manual/manual/preview-latex/* "${AUCTEX_WEBPAGES_DIR}"/manual/preview-latex/.
#+END_src

** =preview= package to CTAN

Upload the =preview= tarball generated with =make preview-ctan= to CTAN as a
"package update" using the [[https://ctan.org/upload][upload form]].

My understanding is that you can use your own name and email in the "Your name"
and "Your email" fields only if you are an authorized uploader of =preview=.
David, Mosè and Arash are authorized, I do not know if other people are
authorized.  If in doubt, ask them.

For the other fields, re-use the details of the [[https://ctan.org/pkg/preview][=preview= page on CTAN]].

- Name of your contribution: =preview=
- Maintainer: The AUCTeX team
- Summary: Extract bits of a LaTeX source for output
- Suggested CTAN directory: =/macros/latex/contrib/preview=
- License type: GNU General Public License, version 3
- Home page: https://www.gnu.org/software/auctex/preview-latex.html
- Bug tracker: https://debbugs.gnu.org/cgi/pkgreport.cgi?package=auctex
- Support: https://lists.gnu.org/mailman/listinfo/auctex
- Announcements: https://lists.gnu.org/mailman/listinfo/info-auctex
- Repository: https://git.savannah.gnu.org/gitweb/?p=auctex.git
- Developers: https://lists.gnu.org/mailman/listinfo/auctex-devel

** Announcement email

An announcement email is sent automatically from =ELPA update= to
=auctex-devel@gnu.org= if the release was successful.

This message can be forwarded to:

- info-auctex@gnu.org, auctex@gnu.org, info-gnu@gnu.org, ctan@dante.de

Include a =Mail-Followup-To= to auctex@gnu.org.  So the header of the email
should be something like (adapt as necessary)

#+BEGIN_SRC message
  From: YOUR NAME <YOUR_EMAIL_ADDRESS@gnu.org>
  To: info-auctex@gnu.org, auctex@gnu.org, info-gnu@gnu.org, ctan@dante.de
  Subject: AUCTeX X.Y released
  Mail-Followup-To: auctex@gnu.org
  --text follows this line--
#+END_SRC

** Bumping required Emacs version

It happens from time to time that AUCTeX requires a newer Emacs
version.  For this, the following files in the main directory has to
be adjusted.

- [ ] =auctex.el= :: Change the ~;; Package-Requires:~ cookie in the header.
- [ ] =tex-site.el.in= :: Change the number after ~emacs-major-version~
- [ ] =tex.el= :: Change the number after ~emacs-major-version~

Other files to be updated accordingly:

- [ ] =doc/faq.texi= :: Adjust the number in this sentence:
  =@AUCTeX{} was tested with @w{GNU Emacs XX.X}=.
- [ ] =doc/install.texi= :: Adjust the number in ~@node Prerequisites~:
  =@item GNU Emacs XX.X or higher=.
- [ ] =doc/preview-faq.texi= :: Adjust the number in ~@section Requirements~
  =@previewlatex{} nominally requires @w{GNU Emacs} with a version of
  at least XX.X.=.
- [ ] =NEWS.org= :: Under a =** Changed= header, add the following:
   =- AUCTeX now requires GNU Emacs XX.1 or higher.=.  AUCTeX supports the last 3
  major releases, so if the current Emacs release is 29.x, AUCTeX supports 29.1,
  28.1 and 27.1.
